version: "2.1"
services:
    daemon:
        build:
          context: ./daemon
        ports:
        - "8002:80"
        links:
          - db:db
        networks:
          - default
        volumes:
          - ./var/log/roman:/var/log/roman
          - /opt/dynatrace/oneagent/agent/lib:/opt/dynatrace/agent/lib64/
        depends_on:
          - db
    www:
        build: .
        ports:
          - "8001:80"
        volumes:
          - ./www:/var/www/html/
        links:
          - db:db
        networks:
          - default
        depends_on:
          - db
    db:
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
          - persistent:/var/lib/mysql
        networks:
          - default
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
          - db:db
        ports:
          - "8000:80"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
